stages:
  - build
  - test

build:
  image: emurze/python_poetry:3.11
  stage: build
  script:
    - poetry install

test:
  image: emurze/python_poetry:3.11
  stage: test
  script:
    - docker compose build -t todo:1 .
    - docker compose up --build
    - docker exec -it todo bash -c "cd src && poetry run coverage run --rcfile ../setup.cfg --data-file logs/.coverage manage.py test && poetry run coverage report --rcfile ../setup.cfg --data-file logs/.coverage"
    - docker exec -it todo bash -c "cd src && poetry run python3 manage.py test apps"
    - docker exec -it todo bash -c "poetry run python3 src/manage.py test tests"
    - docker exec -it todo poetry run python3 -m unittest discover src/utils/