version: "3.5"
services:
  db:
    image: 'postgres:13'
    container_name: 'db'
    networks:
      - backend
    env_file: ./env/.db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  chrome:
   image: selenium/standalone-chrome:latest
   container_name: 'chrome'
   networks:
     - backend
   ports:
     - '4444:4444'
     - '7900:7900'
   privileged: true
   shm_size: 2g
   restart: unless-stopped

  todo:
    build: .
    container_name: 'todo'
    image: 'todo:1'
    command: >
      sh -c 'cd src &&
             poetry run python3 manage.py migrate --no-input &&
             poetry run python3 manage.py createadmin &&
             poetry run python3 manage.py runserver localhost:8080'
    networks:
      - backend
    ports:
      - '8080:8080'
    volumes:
      - ./src:/service/src
      - ./tests:/service/tests
      - app_static:/service/src/static
      - app_media:/service/src/media
    env_file:
      - ./env/.todo.env
    restart: unless-stopped
    depends_on:
      - db
      - chrome

networks:
  backend:

volumes:
  postgres_data:
  app_static:
  app_media:
