name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:13.0-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_PORT: 5432
          POSTGRES_DB: todo
          POSTGRES_USER: todo
          POSTGRES_PASSWORD: 12345678
    env:
      SECRET_KEY: django-insecure-@l8=fm$s+-mjm-2i0)uoly9j+2pctx@+^k27(g$(bqw%i%jk-$
      DEBUG: 1
      LOGGING_LEVEL: DEBUG
      DB_NAME: todo
      DB_USER: todo
      DB_PASSWORD: 12345678
      DB_HOST: localhost
      DB_PORT: 5432

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Insall Poetry
      uses: Gr1N/setup-poetry@v8
      with:
        poetry-version: 1.7.1
    
    - name: Install Dependencies
      run: |
        poetry install

    - name: Create Log File
      run: |
        mkdir src/logs
        touch src/logs/general.log

    - name: Run Unittest Tests
      run: |
        bash -c "cd src && poetry run python3 manage.py test ."
        
